// components/Projects.jsx
import React from "react";

const projects = [
  // Beginner Projects
  {
    id: "phase1-simple-calculator",
    level: "Beginner (0–2 months)",
    title: "Simple Calculator",
    description:
      "Build a console-based calculator supporting addition, subtraction, multiplication, division, and modulus. Skills: Functions, switch-case, input/output, loops.",
    url: "https://youtu.be/1567inlTJKc?si=mBLTS6gKrsbdh8Cu", // Calculator C tutorial
  },
  {
    id: "phase1-number-guessing",
    level: "Beginner (0–2 months)",
    title: "Number Guessing Game",
    description:
      "User guesses a number randomly generated by the program. Provide hints like higher/lower. Skills: Loops, conditional statements, rand() function, basic debugging.",
    url: "https://youtu.be/8GghIa826Qo?si=VASAeaEdlX5sGxFo", // Guess Number Game
  },
  {
    id: "phase1-student-grade-system",
    level: "Beginner (0–2 months)",
    title: "Student Grade Management System",
    description:
      "Store and manage students’ names, IDs, and marks. Display average, highest, lowest grades. Skills: Arrays, structures (struct), loops, basic file I/O.",
    url: "https://youtu.be/E9HHKiwvlH8?si=FJsStVy_IPyChREd", // Student Grade System
  },

  // Intermediate Projects
  {
    id: "phase2-bank-management",
    level: "Intermediate (2–6 months)",
    title: "Bank Management System",
    description:
      "Users can create accounts, deposit, withdraw, and check balance. Store data in files for persistence. Skills: File handling, structures, pointers, functions.",
    url: "https://youtu.be/eezQ7zBijdw?si=BRPYPtpn-gU5dqPW", // Bank System C Tutorial
  },
  {
    id: "phase2-tic-tac-toe",
    level: "Intermediate (2–6 months)",
    title: "Tic-Tac-Toe Game",
    description:
      "Implement a 2-player console game. Detect win, draw, and invalid moves. Skills: Arrays (2D), loops, functions, input validation.",
    url: "https://youtu.be/RBc-NP766KE?si=o_BgH4z22Gpo2q-C", // Tic-Tac-Toe C Tutorial
  },
  {
    id: "phase2-library-management",
    level: "Intermediate (2–6 months)",
    title: "Library Management System",
    description:
      "Maintain books with IDs, titles, authors. Add, remove, search, and list books. Skills: File I/O, dynamic memory, structures, pointers.",
    url: "https://youtu.be/tcq9MIEXpuY?si=MczMwRQ1MUURc0Ps", // Library Management System
  },

  // Advanced Projects
  {
    id: "phase3-linked-list",
    level: "Advanced (6–12 months)",
    title: "Linked List Implementation",
    description:
      "Build a program to perform operations like insertion, deletion, traversal on a linked list. Skills: Pointers, dynamic memory, structures, modular programming.",
    url: "https://youtu.be/6wXZ_m3SbEs?si=asHA0hM28xn7Gy2S", // Linked List C Tutorial
  },
  {
    id: "phase3-simple-shell",
    level: "Advanced (6–12 months)",
    title: "Simple Shell",
    description:
      "Create a minimal command-line shell supporting commands like ls, cd, exit. Skills: Process management (fork, exec), string parsing, loops, system calls.",
    url: "https://youtu.be/yTR00r8vBH8?si=hYfino_b9sKBfhlx", // Shell Scripting & C Tutorial
  },

  {
    id: "phase3-multithreaded-chat",
    level: "Advanced (6–12 months)",
    title: "Multithreaded Chat Server (Socket Programming)",
    description:
      "Build a TCP server-client chat application. Multiple clients can connect concurrently. Skills: Socket programming, pthreads, synchronization, network I/O.",
    url: "https://youtu.be/KEiur5aZnIM?si=-AiimgWnw7BnzuEc", // Chat Server C Tutorial
  },
];

export default function Projects() {
  return (
    <section className="bg-gray-50 py-12 min-h-screen">
      <div className="max-w-6xl mx-auto px-6">
        <header className="mb-8 text-center">
          <h2 className="text-3xl font-extrabold text-gray-900">
            💻 C Programming Project Roadmap
          </h2>
          <p className="mt-2 text-gray-600">
            Step from beginner to advanced C programming projects with detailed tutorials in Hindi & English.
          </p>
        </header>

        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {projects.map((p) => (
            <article
              key={p.id}
              className="group bg-white border border-gray-200 rounded-2xl p-6 shadow-sm hover:shadow-lg hover:-translate-y-1 transition-transform"
              aria-labelledby={`${p.id}-title`}
            >
              <span className="inline-block text-xs font-medium bg-indigo-100 text-indigo-800 px-2 py-1 rounded-full">
                {p.level}
              </span>
              <h3
                id={`${p.id}-title`}
                className="mt-4 text-lg font-semibold text-gray-900 group-hover:text-indigo-600"
              >
                {p.title}
              </h3>
              <p className="mt-2 text-gray-600 text-sm">{p.description}</p>
              <a
                href={p.url}
                target="_blank"
                rel="noopener noreferrer"
                className="mt-4 inline-block text-indigo-600 font-medium hover:underline"
              >
                Watch Tutorial ▶
              </a>
            </article>
          ))}
        </div>

        <footer className="mt-10 text-sm text-gray-500 text-center">
          Build these projects step by step. Focus on pointers, memory management, file I/O, and data structures. Deploy top projects to showcase in your portfolio.
        </footer>
      </div>
    </section>
  );
}
